### ISSUE TITLE
Segmentation fault after recent update

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2150]
**Describe the bug**
I updated my liq code from github yesterday, last update would have been 5 - 6 days ago.

Since then I'm getting a sementation fault on running any script.

I use ladspa, ffmpeg and taglib from the list of recent updates.

gdb backtrace is as follows. 
```
Program received signal SIGSEGV, Segmentation fault.
caml_raise (v=93825002750272) at fail_nat.c:77
77      fail_nat.c: No such file or directory.
(gdb) thread apply all bt

Thread 1 (Thread 0x7fffea3bd340 (LWP 31696)):
#0  caml_raise (v=93825002750272) at fail_nat.c:77
#1  0x0000555555e4bf3f in caml_raise_constant (tag=<optimized out>) at fail_nat.c:88
#2  0x0000555555e022c7 in ocaml_ladspa_descriptor (handle=<optimized out>, n=<optimized out>) at ladspa_stubs.c:111
#3  0x0000555555c7f310 in camlLadspa__descriptors_93 () at src/ladspa.ml:60
#4  0x0000555555c7f32b in camlLadspa__descriptors_93 () at src/ladspa.ml:61
#5  0x00005555559e93a5 in camlLadspa_op__register_plugin_2430 () at src/ladspa.ml:65
#6  0x00005555559e9541 in camlLadspa_op__add_2441 () at operators/ladspa_op.ml:387
#7  0x0000555555da5471 in camlStdlib__list__iter_261 () at list.ml:110
#8  0x0000555555d6793b in camlDtools__Dtools_impl__exec_786 () at src/dtools_impl.ml:455
#9  0x0000555555da5471 in camlStdlib__list__iter_261 () at list.ml:110
#10 0x0000555555d678fe in camlDtools__Dtools_impl__exec_786 () at src/dtools_impl.ml:452
#11 0x0000555555985613 in camlRunner__entry () at main.ml:566
#12 0x000055555597da89 in caml_program ()
#13 0x0000555555e6ee3c in caml_start_program ()
#14 0x0000555555e4bdf4 in caml_startup_common (argv=0x7fffffffe2e8, pooling=<optimized out>, pooling@entry=0) at startup_nat.c:158
#15 0x0000555555e4be3f in caml_startup_exn (argv=<optimized out>) at startup_nat.c:168
#16 caml_startup (argv=<optimized out>) at startup_nat.c:168
#17 0x000055555597b8e2 in main (argc=<optimized out>, argv=<optimized out>) at main.c:41
```

**To Reproduce**
s = sine(432.)

output.dummy(s)

**Expected behavior**
Script to run.

**Version details**
 - OS: [e.g. Debian, OSX] - Ubuntu 20.04
 - Version [e.g. `1.3.4`] latest git main - 2.1.0

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?
OPAM

Thank you.

**Comment by Russsgithub** [comment]
If I uninstall ocaml-ladspa all works fine.

**Comment by Russsgithub** [comment]
ocaml-ladspa rollback to commit ```21a77082c63a00e7b162d492a5fd40ccc3965e38``` (version 2.0) also works fine.

**Comment by toots** [comment]
Thanks for this report. Could you try with the latest commit ([savonet/ocaml-lasapa@a343387](https://github.com/savonet/ocaml-ladspa/commit/a343387c6c5b198f652e6523aca08edfe0794578))
