### ISSUE TITLE
liguidsoap doesn't start

### ISSUE THREAD

**Issue by batphil** [savonet/liquidsoap#220]
I have ubuntu 14.04 and liquidsoap 1.1.1 form repos.

There is this error : 

```
liguidsoap
Traceback (most recent call last):
  File "/var/lib/liguidsoap/liguidsoap.py", line 72, in update
    re.compile('\n').split(self.tel.command('list'))) ]
  File "/var/lib/liguidsoap/client.py", line 13, in command
    ans = self.tel.read_until("END")
  File "/usr/lib/python2.7/telnetlib.py", line 293, in read_until
    return self._read_until_with_poll(match, timeout)
  File "/usr/lib/python2.7/telnetlib.py", line 342, in _read_until_with_poll
    return self.read_very_lazy()
  File "/usr/lib/python2.7/telnetlib.py", line 454, in read_very_lazy
    raise EOFError, 'telnet connection closed'
EOFError: telnet connection closed
```

what's wrong ?

**Comment by batphil** [comment]
I made a video for this problem : https://www.youtube.com/watch?v=mee7RtFnfZ0

**Comment by batphil** [comment]
for some reasons i don't know, it's only works on port 23, even on ports enabled in my firewall/box.
