### ISSUE TITLE
Segfault with mem_usage

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#2427]
The following script is segfaulting:
```
thread.run(every=.1,{print("#{runtime.mem_usage()}")})

output.dummy(blank())
```
The stacktrace is not very informative and changes much between executions:
```
(gdb) where
#0  camlValue__to_string_307 () at src/core/lang/value.ml:67
#1  0x0000555556088e54 in camlValue__fun_898 () at src/core/lang/value.ml:87
#2  0x000055555633d8c1 in camlStdlib__List__map_236 () at list.ml:92
#3  0x000055555633d8d8 in camlStdlib__List__map_236 () at list.ml:92
#4  0x0000555556088ade in camlValue__to_string_307 () at src/core/lang/value.ml:86
#5  0x0000555555c7df9c in camlBuiltins_string__fun_1878 () at src/core/builtins/builtins_string.ml:508
#6  0x00005555560d3c5f in camlEvaluation__apply_741 () at src/core/lang/evaluation.ml:315
#7  0x00005555560d3a68 in camlEvaluation__fun_1916 () at src/core/lang/evaluation.ml:292
#8  0x000055555633d8c1 in camlStdlib__List__map_236 () at list.ml:92
#9  0x000055555633d8d8 in camlStdlib__List__map_236 () at list.ml:92
#10 0x00005555560d3a26 in camlEvaluation__ans_1095 () at src/core/lang/evaluation.ml:292
#11 0x00005555560d3a68 in camlEvaluation__fun_1916 () at src/core/lang/evaluation.ml:292
#12 0x000055555633d8c1 in camlStdlib__List__map_236 () at list.ml:92
#13 0x00005555560d3a26 in camlEvaluation__ans_1095 () at src/core/lang/evaluation.ml:292
#14 0x00005555560d3c5f in camlEvaluation__apply_741 () at src/core/lang/evaluation.ml:315
#15 0x00005555560d3a68 in camlEvaluation__fun_1916 () at src/core/lang/evaluation.ml:292
#16 0x000055555633d8c1 in camlStdlib__List__map_236 () at list.ml:92
#17 0x00005555560d3a26 in camlEvaluation__ans_1095 () at src/core/lang/evaluation.ml:292
#18 0x00005555560d3a68 in camlEvaluation__fun_1916 () at src/core/lang/evaluation.ml:292
#19 0x000055555633d8c1 in camlStdlib__List__map_236 () at list.ml:92
#20 0x00005555560d3a26 in camlEvaluation__ans_1095 () at src/core/lang/evaluation.ml:292
#21 0x00005555560d2afa in camlEvaluation__eval_740 () at src/core/lang/evaluation.ml:287
#22 0x00005555560d3c5f in camlEvaluation__apply_741 () at src/core/lang/evaluation.ml:315
#23 0x00005555560618e4 in camlTutils__finalize_171 () at src/core/tools/tutils.ml:105
#24 0x0000555555c7bc3a in camlBuiltins_thread__fun_510 () at src/core/builtins/builtins_thread.ml:77
#25 0x00005555562eda3c in camlDuppy__fun_2412 () at src/duppy.ml:148
#26 0x00005555562ee720 in camlDuppy__exec_585 () at src/duppy.ml:275
#27 0x00005555562eeb6b in camlDuppy__f_618 () at src/duppy.ml:307
#28 0x00005555562ee973 in camlDuppy__queue_inner_2548 () at src/duppy.ml:357
#29 0x0000555556061d83 in camlTutils__process_705 () at src/core/tools/tutils.ml:164
#30 0x00005555563043c5 in camlThread__fun_314 () at thread.ml:41
#31 0x0000555556495451 in caml_start_program ()
#32 0x000055555648c08d in caml_callback_exn (closure=closure@entry=140737097480408, arg=<optimized out>, arg@entry=1) at callback.c:111
#33 0x0000555556462a80 in caml_thread_start (arg=0x7fffc8003580) at st_stubs.c:547
#34 0x00007ffff7139d80 in start_thread (arg=0x7fffc37fe640) at pthread_create.c:481
#35 0x00007ffff40fa76f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
or
```
(gdb) where
#0  camlStdlib__Printf__fun_229 () at printf.ml:20
#1  0x0000555556301535 in camlDtools__Dtools_impl__print_1375 () at src/dtools_impl.ml:679
#2  0x00005555563585ba in camlStdlib__Queue__iter_143 () at queue.ml:121
#3  0x00005555563017e3 in camlDtools__Dtools_impl__flush_1440 () at queue.ml:124
#4  0x0000555556301843 in camlDtools__Dtools_impl__f_1446 () at src/dtools_impl.ml:728
#5  0x00005555563043c5 in camlThread__fun_314 () at thread.ml:41
#6  0x0000555556495451 in caml_start_program ()
#7  0x000055555648c08d in caml_callback_exn (closure=closure@entry=140737097515144, arg=<optimized out>, arg@entry=1) at callback.c:111
#8  0x0000555556462a80 in caml_thread_start (arg=0x555557c3b4c0) at st_stubs.c:547
#9  0x00007ffff7139d80 in start_thread (arg=0x7fffd1b37640) at pthread_create.c:481
#10 0x00007ffff40fa76f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by smimram** [comment]
Note that regular running is not necessary, one run is enough to trigger the segv:
```
thread.run({print("Memory: #{runtime.mem_usage()}")})
```
