### ISSUE TITLE
Liquidsoap Deadlock

### ISSUE THREAD

**Issue by jd-buys** [savonet/liquidsoap#2572]
**Describe the bug**
The liquidsoap process hangs/deadlocks every now and then. 
I have not been able to find anything that causes it so I can't reproduce it, but it happens quite often.

**To Reproduce**
A minimal script to reproduce the issue is the most efficient way to have your bug addressed and fixed very quickly!

**Expected behavior**

**Version details**
 - OS: CentOS Stream 9
 - Version 2.1.0

**Install method**
I installed liquidsoap from source and all the dependencies with opam.

Here is the GDB stacktrace that I got.

```
Thread 9 (Thread 0x7f918f7fe640 (LWP 2188506) "liquidsoap"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f9184002b98) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f9184002b98, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f91afd1f98f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f9184002b98, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f91afd22130 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1573be0, cond=0x7f9184002b70) at pthread_cond_wait.c:504
#4  ___pthread_cond_wait (cond=cond@entry=0x7f9184002b70, mutex=mutex@entry=0x1573be0) at pthread_cond_wait.c:619
#5  0x0000000000c88d1f in st_condvar_wait (m=0x1573be0, c=0x7f9184002b70) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:290
#6  caml_condition_wait (wcond=<optimized out>, wmut=<optimized out>) at st_stubs.c:871
#7  0x0000000000b859e5 in camlDuppy__f_606 () at src/duppy.ml:341
#8  0x0000000000b85654 in camlDuppy__queue_inner_2535 () at src/duppy.ml:357
#9  0x000000000090c8a3 in camlTutils__process_703 () at tools/tutils.ml:164
#10 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#11 0x0000000000cb0f80 in caml_start_program ()
#12 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263372187856, arg=<optimized out>, arg@entry=1) at callback.c:111
#13 0x0000000000c882e0 in caml_thread_start (arg=0x7f9188006aa0) at st_stubs.c:539
#14 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#15 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 8 (Thread 0x7f918ffff640 (LWP 2188505) "liquidsoap"):
#0  0x00007f91afdc567f in __GI___poll (fds=fds@entry=0x7f917404d400, nfds=nfds@entry=6, timeout=timeout@entry=4999) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000000000c7aa51 in caml_poll (_read=<optimized out>, _write=<optimized out>, _err=<optimized out>, _timeout=<optimized out>) at duppy_stubs.c:95
#2  0x0000000000b83e30 in camlDuppy__poll_125 () at src/duppy.ml:37
#3  0x0000000000b84f7c in camlDuppy__f_521 () at src/duppy.ml:208
#4  0x0000000000b84b7d in camlDuppy__process_511 () at src/duppy.ml:229
#5  0x0000000000b858c3 in camlDuppy__f_606 () at src/duppy.ml:326
#6  0x0000000000b85654 in camlDuppy__queue_inner_2535 () at src/duppy.ml:357
#7  0x000000000090c8a3 in camlTutils__process_703 () at tools/tutils.ml:164
#8  0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#9  0x0000000000cb0f80 in caml_start_program ()
#10 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263289150976, arg=<optimized out>, arg@entry=1) at callback.c:111
#11 0x0000000000c882e0 in caml_thread_start (arg=0x7f9188006710) at st_stubs.c:539
#12 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#13 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7f919494f640 (LWP 2188504) "liquidsoap"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f9178002b9c) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f9178002b9c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f91afd1f98f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f9178002b9c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f91afd22130 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1573be0, cond=0x7f9178002b70) at pthread_cond_wait.c:504
#4  ___pthread_cond_wait (cond=cond@entry=0x7f9178002b70, mutex=mutex@entry=0x1573be0) at pthread_cond_wait.c:619
#5  0x0000000000c88d1f in st_condvar_wait (m=0x1573be0, c=0x7f9178002b70) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:290
#6  caml_condition_wait (wcond=<optimized out>, wmut=<optimized out>) at st_stubs.c:871
#7  0x0000000000b859e5 in camlDuppy__f_606 () at src/duppy.ml:341
#8  0x0000000000b85654 in camlDuppy__queue_inner_2535 () at src/duppy.ml:357
#9  0x000000000090c8a3 in camlTutils__process_703 () at tools/tutils.ml:164
#10 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#11 0x0000000000cb0f80 in caml_start_program ()
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263289151152, arg=<optimized out>, arg@entry=1) at callback.c:111
#13 0x0000000000c882e0 in caml_thread_start (arg=0x7f9188006380) at st_stubs.c:539
#14 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#15 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f9195150640 (LWP 2188503) "liquidsoap"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f9180002b98) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f9180002b98, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f91afd1f98f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f9180002b98, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f91afd22130 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1573be0, cond=0x7f9180002b70) at pthread_cond_wait.c:504
#4  ___pthread_cond_wait (cond=cond@entry=0x7f9180002b70, mutex=mutex@entry=0x1573be0) at pthread_cond_wait.c:619
#5  0x0000000000c88d1f in st_condvar_wait (m=0x1573be0, c=0x7f9180002b70) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:290
#6  caml_condition_wait (wcond=<optimized out>, wmut=<optimized out>) at st_stubs.c:871
#7  0x0000000000b859e5 in camlDuppy__f_606 () at src/duppy.ml:341
#8  0x0000000000b85654 in camlDuppy__queue_inner_2535 () at src/duppy.ml:357
#9  0x000000000090c8a3 in camlTutils__process_703 () at tools/tutils.ml:164
#10 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#11 0x0000000000cb0f80 in caml_start_program ()
#12 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263372193384, arg=<optimized out>, arg@entry=1) at callback.c:111
#13 0x0000000000c882e0 in caml_thread_start (arg=0x7f9188005ff0) at st_stubs.c:539
#14 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#15 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f9195951640 (LWP 2188502) "liquidsoap"):
#0  __GI___libc_write (nbytes=79, buf=0x7f917c09db40, fd=2) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __GI___libc_write (fd=2, buf=0x7f917c09db40, nbytes=79) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007f91afd1a76d in _IO_new_file_write (f=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=0x7f917c09db40, n=79) at fileops.c:1181
#3  0x00007f91afd19ae6 in new_do_write (fp=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=0x7f917c09db40 "[mp3float @ 0x7f917c173fc0] Could not update timestamps for discarded samples.\n\nr\272\346\066\v\275\064\067I\372\242\066\314\367\244\066o\036\061\067\062\335T6~p\"\266\b#\240\066\205\362e6\214\033\270\265\217\347\255\066\217\356\370\066\025\244\222\066\256", to_do=to_do@entry=79) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#4  0x00007f91afd1b809 in _IO_new_do_write (to_do=79, data=<optimized out>, fp=<optimized out>) at fileops.c:423
#5  _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=79) at fileops.c:423
#6  0x00007f91afd1adb6 in _IO_new_file_xsputn (n=51, data=<optimized out>, f=<optimized out>) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#7  _IO_new_file_xsputn (f=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=<optimized out>, n=51) at fileops.c:1197
#8  0x00007f91afd0f9ad in __GI__IO_fputs (str=0x7f919594df34 "Could not update timestamps for discarded samples.\n", fp=0x7f91afe7e6a0 <_IO_2_1_stderr_>) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#9  0x00007f91b1cb3e5f in av_log_default_callback () at /lib64/libavutil.so.57
#10 0x00007f91b1cafb73 in av_log () at /lib64/libavutil.so.57
#11 0x00007f91b0a62013 in decode_receive_frame_internal () at /lib64/libavcodec.so.59
#12 0x00007f91b0a621f8 in avcodec_send_packet () at /lib64/libavcodec.so.59
#13 0x0000000000c51474 in decode_packet (frame=0x7f917c11ae40, packet=0x7f917c1007c0, stream=<optimized out>, av=0x7f917c09fb20) at av_stubs.c:1015
#14 ocaml_av_read_input (_packet=<optimized out>, _frame=<optimized out>, _av=<optimized out>) at av_stubs.c:1206
#15 0x0000000000ad72d9 in camlAv__read_input_inner_1445 () at av/av.ml:216
#16 0x00000000006b7490 in camlFfmpeg_decoder__f_1239 () at decoder/ffmpeg_decoder.ml:662
#17 0x00000000008e4d9c in camlDecoder__fill_2127 () at decoder/decoder.ml:506
#18 0x000000000076e194 in camlRequest_source__fun_2120 () at sources/request_source.ml:201
#19 0x000000000090c329 in camlTutils__mutexify_106 () at tools/tutils.ml:95
#20 0x000000000076e37c in camlRequest_source__fun_2172 () at sources/request_source.ml:244
#21 0x000000000090c329 in camlTutils__mutexify_106 () at tools/tutils.ml:95
#22 0x000000000076b6a8 in camlRequest_source__fun_2152 () at sources/request_source.ml:227
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x000000000076bd07 in camlRequest_source__fun_2364 () at sources/request_source.ml:506
#24 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#25 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#26 0x000000000072b8f6 in camlConversion__fun_732 () at conversions/conversion.ml:61
#27 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#28 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#29 0x0000000000727038 in camlMap_metadata__fun_1137 () at operators/map_metadata.ml:51
#30 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#31 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#32 0x00000000007041bb in camlCuepoint__fun_1506 () at operators/cuepoint.ml:170
#33 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#34 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#35 0x0000000000728238 in camlInsert_metadata__fun_1433 () at operators/insert_metadata.ml:134
#36 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#37 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#38 0x000000000071ba86 in camlSwitch__fun_2115 () at operators/switch.ml:254
#39 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#40 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#41 0x000000000071ba86 in camlSwitch__fun_2115 () at operators/switch.ml:254
#42 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#43 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#44 0x000000000072b8f6 in camlConversion__fun_732 () at conversions/conversion.ml:61
#45 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#46 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#47 0x0000000000726488 in camlOn_end__fun_1098 () at operators/on_end.ml:37
#48 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#49 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#50 0x0000000000723598 in camlOn_metadata__fun_1096 () at operators/on_metadata.ml:35
#51 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#52 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#53 0x0000000000723ea4 in camlOn_track__fun_1008 () at operators/on_track.ml:36
#54 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#55 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#56 0x00000000006fbe04 in camlAmplify__fun_2282 () at operators/amplify.ml:39
#57 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#58 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#59 0x00000000008f2aa2 in camlVFrame__get_content_418 () at stream/vFrame.ml:45
#60 0x00000000006ed721 in camlVideo_effects__fun_3323 () at operators/video_effects.ml:37
#61 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#62 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#63 0x0000000000723598 in camlOn_metadata__fun_1096 () at operators/on_metadata.ml:35
#64 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#65 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#66 0x0000000000723ea4 in camlOn_track__fun_1008 () at operators/on_track.ml:36
#67 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#68 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#69 0x0000000000726488 in camlOn_end__fun_1098 () at operators/on_end.ml:37
#70 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#71 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#72 0x00000000006fbe04 in camlAmplify__fun_2282 () at operators/amplify.ml:39
#73 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#74 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
--Type <RET> for more, q to quit, c to continue without paging--
#75 0x00000000008f2aa2 in camlVFrame__get_content_418 () at stream/vFrame.ml:45
#76 0x00000000006ed721 in camlVideo_effects__fun_3323 () at operators/video_effects.ml:37
#77 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#78 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#79 0x000000000071764b in camlCross__fun_3026 () at operators/cross.ml:271
#80 0x0000000000718068 in camlCross__fun_2993 () at operators/cross.ml:223
#81 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#82 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#83 0x00000000006fbe04 in camlAmplify__fun_2282 () at operators/amplify.ml:39
#84 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#85 0x00000000008d5e31 in camlSource__fun_3264 () at source.ml:677
#86 0x000000000071ba86 in camlSwitch__fun_2115 () at operators/switch.ml:254
#87 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#88 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#89 0x000000000071ba86 in camlSwitch__fun_2115 () at operators/switch.ml:254
#90 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#91 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#92 0x000000000072525e in camlOn_frame__fun_2238 () at operators/on_frame.ml:34
#93 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#94 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#95 0x000000000071ba86 in camlSwitch__fun_2115 () at operators/switch.ml:254
#96 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#97 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#98 0x000000000072b8f6 in camlConversion__fun_732 () at conversions/conversion.ml:61
#99 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#100 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#101 0x0000000000726488 in camlOn_end__fun_1098 () at operators/on_end.ml:37
#102 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#103 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#104 0x00000000006e8813 in camlNoblank__fun_2188 () at operators/noblank.ml:98
#105 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#106 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#107 0x0000000000723598 in camlOn_metadata__fun_1096 () at operators/on_metadata.ml:35
#108 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#109 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#110 0x0000000000727f18 in camlInsert_metadata__fun_1392 () at operators/insert_metadata.ml:74
#111 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#112 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#113 0x0000000000723598 in camlOn_metadata__fun_1096 () at operators/on_metadata.ml:35
#114 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#115 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#116 0x0000000000723ea4 in camlOn_track__fun_1008 () at operators/on_track.ml:36
#117 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#118 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#119 0x00000000006fbe04 in camlAmplify__fun_2282 () at operators/amplify.ml:39
#120 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#121 0x00000000008d6024 in camlSource__fun_3264 () at source.ml:660
#122 0x00000000008f2aa2 in camlVFrame__get_content_418 () at stream/vFrame.ml:45
#123 0x00000000006ed721 in camlVideo_effects__fun_3323 () at operators/video_effects.ml:37
#124 0x00000000008d62df in camlSource__fun_3189 () at source.ml:589
#125 0x00000000008d5e31 in camlSource__fun_3264 () at source.ml:677
#126 0x000000000074eeec in camlOutput__fun_2014 () at outputs/output.ml:165
--Type <RET> for more, q to quit, c to continue without paging--
#127 0x00000000008d3ea2 in camlClock__fun_2254 () at clock.ml:299
#128 0x0000000000bd4e28 in camlStdlib__list__fold_left_275 () at list.ml:121
#129 0x00000000008d1b0c in camlClock__fun_2203 () at clock.ml:296
#130 0x00000000008d3bc3 in camlClock__loop_1142 () at clock.ml:266
#131 0x00000000008d1edd in camlClock__fun_2180 () at clock.ml:269
#132 0x000000000090c8a3 in camlTutils__process_703 () at tools/tutils.ml:164
#133 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#134 0x0000000000cb0f80 in caml_start_program ()
#135 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263372195808, arg=<optimized out>, arg@entry=1) at callback.c:111
#136 0x0000000000c882e0 in caml_thread_start (arg=0x7f9188005c60) at st_stubs.c:539
#137 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#138 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f9196152640 (LWP 2188501) "liquidsoap"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x1573588) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x1573588, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f91afd1f98f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x1573588, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f91afd22130 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1572180, cond=0x1573560) at pthread_cond_wait.c:504
#4  ___pthread_cond_wait (cond=cond@entry=0x1573560, mutex=mutex@entry=0x1572180) at pthread_cond_wait.c:619
#5  0x0000000000c88d1f in st_condvar_wait (m=0x1572180, c=0x1573560) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:290
#6  caml_condition_wait (wcond=<optimized out>, wmut=<optimized out>) at st_stubs.c:871
#7  0x000000000090db18 in camlTutils__fun_2283 () at tools/tutils.ml:327
#8  0x000000000090c329 in camlTutils__mutexify_106 () at tools/tutils.ml:95
#9  0x0000000000b8e708 in camlDtools__Dtools_impl__thread_892 () at src/dtools_impl.ml:497
#10 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#11 0x0000000000cb0f80 in caml_start_program ()
#12 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263373582360, arg=<optimized out>, arg@entry=1) at callback.c:111
#13 0x0000000000c882e0 in caml_thread_start (arg=0x15d3c20) at st_stubs.c:539
#14 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#15 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7f9196953640 (LWP 2188500) "liquidsoap"):
#0  0x00007f91afdc7ddd in __GI___select (nfds=nfds@entry=0, readfds=readfds@entry=0x0, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7f9196952430) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x0000000000c876b1 in caml_thread_tick (arg=<optimized out>) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:388
#2  0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#3  0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f9197154640 (LWP 2188499) "liquidsoap"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x1518b28) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x1518b28, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f91afd1f98f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x1518b28, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f91afd22130 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x1518ad0, cond=0x1518b00) at pthread_cond_wait.c:504
#4  ___pthread_cond_wait (cond=cond@entry=0x1518b00, mutex=mutex@entry=0x1518ad0) at pthread_cond_wait.c:619
#5  0x0000000000c88d1f in st_condvar_wait (m=0x1518ad0, c=0x1518b00) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:290
#6  caml_condition_wait (wcond=<optimized out>, wmut=<optimized out>) at st_stubs.c:871
#7  0x0000000000b8f6d2 in camlDtools__Dtools_impl__fun_2762 () at src/dtools_impl.ml:734
#8  0x0000000000b8f4ca in camlDtools__Dtools_impl__mutexify_1402 () at src/dtools_impl.ml:702
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x0000000000b8f66f in camlDtools__Dtools_impl__f_1422 () at src/dtools_impl.ml:730
#10 0x0000000000bc8b35 in camlThread__fun_314 () at thread.ml:41
#11 0x0000000000cb0f80 in caml_start_program ()
#12 0x0000000000ca756d in caml_callback_exn (closure=closure@entry=140263373582656, arg=<optimized out>, arg@entry=1) at callback.c:111
#13 0x0000000000c882e0 in caml_thread_start (arg=0x15e21e0) at st_stubs.c:539
#14 0x00007f91afd22d92 in start_thread (arg=<optimized out>) at pthread_create.c:443
#15 0x00007f91afcc29e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f91aa0c80c0 (LWP 2188494) "liquidsoap"):
#0  0x00007f91afcd903a in __GI___sigtimedwait (set=set@entry=0x7ffec2e81ef0, info=info@entry=0x7ffec2e81e30, timeout=timeout@entry=0x0) at ../sysdeps/unix/sysv/linux/sigtimedwait.c:61
#1  0x00007f91afcd867c in __GI___sigwait (set=set@entry=0x7ffec2e81ef0, sig=sig@entry=0x7ffec2e81eec) at ../sysdeps/unix/sysv/linux/sigwait.c:28
#2  0x0000000000c87ef1 in caml_wait_signal (sigs=<optimized out>) at /home/liquidsoap/.opam/4.12.1/.opam-switch/build/ocaml-base-compiler.4.12.1/otherlibs/systhreads/st_posix.h:474
#3  0x0000000000b8e438 in camlDtools__Dtools_impl__wait_signal_789 () at src/dtools_impl.ml:471
#4  0x0000000000b8e5e1 in camlDtools__Dtools_impl__main_885 () at src/dtools_impl.ml:507
#5  0x0000000000b8e83a in camlDtools__Dtools_impl__catch_900 () at src/dtools_impl.ml:512
#6  0x000000000065d6cb in camlMain__fun_2302 () at main.ml:563
#7  0x0000000000bd4d71 in camlStdlib__list__iter_261 () at list.ml:110
#8  0x0000000000b8e33b in camlDtools__Dtools_impl__exec_786 () at src/dtools_impl.ml:455
#9  0x0000000000bd4d71 in camlStdlib__list__iter_261 () at list.ml:110
#10 0x0000000000b8e378 in camlDtools__Dtools_impl__exec_786 () at src/dtools_impl.ml:458
#11 0x0000000000bd4d71 in camlStdlib__list__iter_261 () at list.ml:110
#12 0x0000000000b8e378 in camlDtools__Dtools_impl__exec_786 () at src/dtools_impl.ml:458
#13 0x000000000065b883 in camlRunner__entry () at main.ml:572
#14 0x0000000000653a49 in caml_program ()
#15 0x0000000000cb0f80 in caml_start_program ()
#16 0x0000000000c8ff54 in caml_startup_common (argv=0x7ffec2e822f8, pooling=<optimized out>, pooling@entry=0) at startup_nat.c:161
#17 0x0000000000c8ffdb in caml_startup_exn (argv=<optimized out>) at startup_nat.c:168
#18 caml_startup (argv=<optimized out>) at startup_nat.c:173
#19 caml_main (argv=<optimized out>) at startup_nat.c:180
#20 0x0000000000650b7c in main (argc=<optimized out>, argv=<optimized out>) at main.c:41
```

**Comment by toots** [comment]
Hi!

Thanks for reporting with a stack trace!

This looks suspicious to me:
```
Thread 5 (Thread 0x7f9195951640 (LWP 2188502) "liquidsoap"):
#0  __GI___libc_write (nbytes=79, buf=0x7f917c09db40, fd=2) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __GI___libc_write (fd=2, buf=0x7f917c09db40, nbytes=79) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007f91afd1a76d in _IO_new_file_write (f=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=0x7f917c09db40, n=79) at fileops.c:1181
#3  0x00007f91afd19ae6 in new_do_write (fp=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=0x7f917c09db40 "[mp3float @ 0x7f917c173fc0] Could not update timestamps for discarded samples.\n\nr\272\346\066\v\275\064\067I\372\242\066\314\367\244\066o\036\061\067\062\335T6~p\"\266\b#\240\066\205\362e6\214\033\270\265\217\347\255\066\217\356\370\066\025\244\222\066\256", to_do=to_do@entry=79) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#4  0x00007f91afd1b809 in _IO_new_do_write (to_do=79, data=<optimized out>, fp=<optimized out>) at fileops.c:423
#5  _IO_new_do_write (fp=<optimized out>, data=<optimized out>, to_do=79) at fileops.c:423
#6  0x00007f91afd1adb6 in _IO_new_file_xsputn (n=51, data=<optimized out>, f=<optimized out>) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#7  _IO_new_file_xsputn (f=0x7f91afe7e6a0 <_IO_2_1_stderr_>, data=<optimized out>, n=51) at fileops.c:1197
#8  0x00007f91afd0f9ad in __GI__IO_fputs (str=0x7f919594df34 "Could not update timestamps for discarded samples.\n", fp=0x7f91afe7e6a0 <_IO_2_1_stderr_>) at /usr/src/debug/glibc-2.34-39.el9.x86_64/libio/libioP.h:947
#9  0x00007f91b1cb3e5f in av_log_default_callback () at /lib64/libavutil.so.57
#10 0x00007f91b1cafb73 in av_log () at /lib64/libavutil.so.57
#11 0x00007f91b0a62013 in decode_receive_frame_internal () at /lib64/libavcodec.so.59
#12 0x00007f91b0a621f8 in avcodec_send_packet () at /lib64/libavcodec.so.59
```
It looks like ffmpeg is trying to write some logs but it's possible it's getting stuck?

I would suggest next time this happens to take two stack trace and see if anything has changed to confirm that it's indeed stuck logging.
