### ISSUE TITLE
Segfault related to flac decoder?

### ISSUE THREAD

**Issue by hjri** [savonet/liquidsoap#356]
Liquidsoap sometimes crashes without any useful information - application just quits with 139 exit code. After several crashes I started running liquidsoap trough gdb just to see what happened. Here's the stack trace of one of the crashes (i'll post more in separate issues) 

```
Thread 2 "liquidsoap" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee808700 (LWP 26190)]
0x0000000000796c14 in caml_copy_string ()
(gdb) bt
#0  0x0000000000796c14 in caml_copy_string ()
#1  0x00007ffff0bcaf35 in ocaml_flac_decoder_info () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#2  0x00007ffff0bc910c in camlFlac__info_1053 () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#3  0x00007ffff0bc919d in camlFlac__init_1060 () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#4  0x00007ffff0bc9342 in camlFlac__create_from_fd_1077 () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#5  0x00007ffff0bc7c08 in camlFlac_decoder__fun_1411 () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#6  0x00000000006898c1 in camlTutils__finalize_1087 ()
#7  0x00007ffff0bc80c9 in camlFlac_decoder__fun_1416 () from /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs
#8  0x00000000006789f4 in camlDecoder__fun_1275 ()
#9  0x000000000074a831 in camlList__iter_1061 ()
#10 0x00000000006797cc in camlDecoder__get_file_decoder_1150 ()
#11 0x00000000006751bd in camlRequest__check_decodable_1264 ()
#12 0x0000000000677088 in camlRequest__create_1343 ()
#13 0x000000000062fab3 in camlPlaylist__fun_1789 ()
#14 0x00000000006353cf in camlRequest_source__fun_1889 ()
#15 0x000000000063580c in camlRequest_source__fun_1876 ()
#16 0x0000000000724244 in camlDuppy__task_1140 ()
#17 0x0000000000722dcc in camlDuppy__fun_1655 ()
#18 0x0000000000726905 in camlDuppy__exec_1107 ()
#19 0x0000000000726aeb in camlDuppy__queue_1114 ()
#20 0x000000000068915e in camlTutils__queue_1190 ()
#21 0x0000000000688a0a in camlTutils__fun_1346 ()
#22 0x000000000073e4f9 in camlThread__fun_1081 ()
#23 0x00000000007a44c2 in caml_start_program ()
#24 0x0000000000c417c0 in ?? ()
#25 0x0000000000000000 in ?? ()
```

**Comment by hjri** [comment]
Note, that flacs are played normally, I only had some problems with two particular AAC files so far. I do not know what file caused this problem, last messages in log were:
```
2016/10/09 07:05:54 [radio(dot)m3u:3] Prepared "/track2.flac" (RID 3).
2016/10/09 07:10:01 [decoder:3] Method "MAD" accepted "/track1.mp3".
2016/10/09 07:10:15 [radio(dot)m3u:3] Finished with "/track2.flac".
2016/10/09 07:10:15 [radio(dot)m3u:3] Prepared "/track1.mp3" (RID 1).
```
(track filenames replaced)

**Comment by toots** [comment]
Any update on this one? Still happening?

**Comment by hjri** [comment]
Sorry, but unfortunately, while it was happening I used a workaround by simply removing the offending song from playlist, and nowadays I don't use liquidsoap, so I don't really know. And for further disappointment I don't remember what file was is and playlist wasn't under any vcs so I can't look up changes I made to it, so I can't really try to reproduce it.

**Comment by toots** [comment]
No worries, thanks for the update!
