### ISSUE TITLE
`2.3.0` - Segfault with Ubuntu package .deb.

### ISSUE THREAD

**Issue by gAlleb** [savonet/liquidsoap#3882]
Segmentation fault with latest Ubuntu package .deb (including [improve-errors](https://github.com/savonet/liquidsoap/tree/improve-errors)). LS crashes after few minutes with `Segmentation fault (core dumped)`. Sometimes it takes longer. It's hard to tell what causes this.

Stacktrace:

```ruby
Thread 6 "liquidsoap" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc1445640 (LWP 1033711)]
0x00005555570fe46c in caml_darken ()
(gdb) backtrace
#0  0x00005555570fe46c in caml_darken ()
#1  0x000055555710543e in caml_do_local_roots ()
#2  0x00005555571054c1 in caml_do_roots ()
#3  0x00005555570fde5d in ?? ()
#4  0x00005555570ee2b8 in caml_try_run_on_all_domains_with_spin_work ()
#5  0x00005555570ff89e in ?? ()
#6  0x00005555570ffa66 in caml_major_collection_slice ()
#7  0x00005555570edc15 in caml_poll_gc_work ()
#8  0x000055555710333d in caml_check_urgent_gc ()
#9  0x00005555570e615d in caml_alloc_string ()
#10 <signal handler called>
#11 0x000055555668d77a in camlVorbis.anon_fn$5bvorbis.ml$3a210$2c10$2d$2d148$5d_700 ()
#12 <signal handler called>
#13 0x00005555570eb06c in caml_callback_exn ()
#14 0x00005555570eb5ad in caml_callback ()
#15 0x0000555556ff4d61 in ?? ()
#16 0x00007ffff7f67cf9 in _get_next_page.constprop.0 () from /usr/local/lib/libvorbisfile.so.3
#17 0x00007ffff7f6840d in _fetch_headers () from /usr/local/lib/libvorbisfile.so.3
#18 0x00007ffff7f69f75 in _ov_open1 () from /usr/local/lib/libvorbisfile.so.3
#19 0x00007ffff7f6ab03 in ov_open_callbacks () from /usr/local/lib/libvorbisfile.so.3
#20 0x0000555556ff686b in ocaml_vorbis_open_dec_stream ()
#21 <signal handler called>
#22 0x000055555668d709 in camlVorbis.openfile_with_fd_688 ()
#23 0x000055555668d866 in camlVorbis.openfile_752 ()
#24 0x000055555668b5d3 in camlVorbisduration.duration_5 ()
#25 0x0000555556b5e99a in camlRequest.anon_fn$5brequest.ml$3a148$2c25$2d$2d212$5d_472 ()
#26 0x0000555556e917a8 in camlLiquidsoap_lang__Plug.iter_458 ()
#27 0x0000555556b5e919 in camlRequest.duration_456 ()
#28 0x00005555567ab9d7 in camlBuiltins_request.anon_fn$5bbuiltins_request.ml$3a227$2c4$2d$2d203$5d_1350 ()
#29 0x0000555556e86bba in camlLiquidsoap_lang__Evaluation.apply_742 ()
#30 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#31 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#32 0x0000555556e88239 in camlLiquidsoap_lang__Evaluation.anon_fn$5bevaluation.ml$3a356$2c27$2d$2d70$5d_1347 ()
#33 0x0000555556f6e7d3 in camlStdlib__List.map_508 ()
#34 0x0000555556e881cd in camlLiquidsoap_lang__Evaluation.ans_1322 ()
#35 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#36 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#37 0x0000555556e874ee in camlLiquidsoap_lang__Evaluation.eval_base_term_743 ()
#38 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#39 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#40 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#41 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#42 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#43 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#44 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#45 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#46 0x0000555556e86bba in camlLiquidsoap_lang__Evaluation.apply_742 ()
#47 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#48 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#49 0x0000555556e88239 in camlLiquidsoap_lang__Evaluation.anon_fn$5bevaluation.ml$3a356$2c27$2d$2d70$5d_1347 ()
#50 0x0000555556f6e7bd in camlStdlib__List.map_508 ()
#51 0x0000555556e881cd in camlLiquidsoap_lang__Evaluation.ans_1322 ()
#52 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#53 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#54 0x0000555556e88239 in camlLiquidsoap_lang__Evaluation.anon_fn$5bevaluation.ml$3a356$2c27$2d$2d70$5d_1347 ()
#55 0x0000555556f6e77d in camlStdlib__List.map_508 ()
#56 0x0000555556e881cd in camlLiquidsoap_lang__Evaluation.ans_1322 ()
#57 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#58 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#59 0x0000555556e87485 in camlLiquidsoap_lang__Evaluation.eval_base_term_743 ()
#60 0x0000555556e882a9 in camlLiquidsoap_lang__Evaluation.eval_term_744 ()
#61 0x0000555556e88365 in camlLiquidsoap_lang__Evaluation.eval_745 ()
#62 0x0000555556e86bba in camlLiquidsoap_lang__Evaluation.apply_742 ()
#63 0x000055555678d2ca in camlBuiltins_thread.fn_1393 ()
```

**Version details**
Ubuntu 22.04

**Install method**
deb

**Comment by toots** [comment]
Thanks for reporting. Do you have a specific script you're using for this?
