### ISSUE TITLE
liquidsoap-1.3.7 hangs during shutdown.

### ISSUE THREAD

**Issue by crocket** [savonet/liquidsoap#894]
**Describe the bug**

liquidsoap-1.3.7 seems to freeze at https://github.com/savonet/liquidsoap/blob/1a76f535e742ed7115036dcea1f89b5a8c2bdfa3/src/tools/tutils.ml#L201 during shutdown. It has to be killed by `kill -9`.

```
> liquidsoap 'output.dummy(blank())'
2019/07/24 16:05:40 >>> LOG START
2019/07/24 16:05:40 [main:3] Liquidsoap 1.3.7
2019/07/24 16:05:40 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.2.3 dtools=0.4.1 duppy=0.6.0 duppy.syntax=0.6.0 cry=0.6.2 mm=0.4.0 xmlplaylist=0.1.4 ogg=0.5.2 vorbis=0.7.0 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 ffmpeg=0.2.1 bjack=0.1.5 alsa=0.2.3 samplerate=0.1.4 ssl=0.5.3 camomile=[unspecified] sdl=0.9.1
2019/07/24 16:05:40 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2019/07/24 16:05:40 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/07/24 16:05:40 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/07/24 16:05:40 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/07/24 16:05:40 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/07/24 16:05:40 [threads:3] Created thread "generic queue #1".
2019/07/24 16:05:40 [threads:3] Created thread "generic queue #2".
2019/07/24 16:05:40 [threads:3] Created thread "non-blocking queue #1".
2019/07/24 16:05:40 [threads:3] Created thread "non-blocking queue #2".
2019/07/24 16:05:40 [threads:3] Created thread "wallclock_main" (1 total).
2019/07/24 16:05:40 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.

(Press Ctrl+C)

2019/07/24 16:05:43 [main:3] Shutdown started!
2019/07/24 16:05:43 [main:3] Waiting for threads to terminate...
2019/07/24 16:05:43 [threads:3] Shuting down thread wallclock_main
2019/07/24 16:05:43 [clock.wallclock_main:3] Streaming loop stopped.
2019/07/24 16:05:43 [threads:3] Thread "wallclock_main" terminated (0 remaining).
2019/07/24 16:05:43 [main:3] Threads terminated.
2019/07/24 16:05:43 [threads:3] Shutting down scheduler...
2019/07/24 16:05:43 [threads:3] Scheduler shut down.
2019/07/24 16:05:43 [threads:3] Shutting down queues...
2019/07/24 16:05:43 [threads:3] Thread "non-blocking queue #1" terminated.

(Press Ctrl+Z)

Job 1, 'liquidsoap 'output.dummy(blank(…' has stopped

> kill -9 %1
fish: Job 1, “liquidsoap 'output.dummy(blank(…” terminated by signal SIGKILL (Forced quit)
```

**To Reproduce**

Execute any script. Anything. `liquidsoap 'output.dummy(blank())'` is the simplest.

**Expected behavior**

It should shut down cleanly as liquidsoap-1.3.1 does.

**Version details**

OS: Gentoo Linux

```
> emerge -p liquidsoap
[ebuild  N    ] media-libs/sdl-mixer-1.2.12-r4
[ebuild  N    ] dev-lang/ocaml-4.04.2-r1
[ebuild  N    ] x11-libs/gtkglarea-2.1.0
[ebuild  N    ] app-text/gtkspell-2.0.16
[ebuild  N    ] media-libs/libart_lgpl-2.3.21-r3
[ebuild  N    ] media-libs/sdl-image-1.2.12-r2
[ebuild  N    ] media-libs/sdl-ttf-2.0.11-r1
[ebuild  N    ] dev-ml/findlib-1.7.1
[ebuild  N    ] dev-ml/ocamlbuild-0.10.1
[ebuild  N    ] dev-ml/xml-light-2.2-r3
[ebuild  N    ] gnome-base/libgnomecanvas-2.30.3-r1
[ebuild  N    ] dev-ml/camlp4-4.04_p1
[ebuild  N    ] dev-ml/ocaml-ssl-0.5.3
[ebuild  N    ] dev-ml/cppo-1.4.1
[ebuild  N    ] dev-ml/pcre-ocaml-7.2.3
[ebuild  N    ] dev-ml/ocaml-ffmpeg-0.2.1
[ebuild  N    ] dev-ml/ocaml-re-1.7.1
[ebuild  N    ] dev-ml/uchar-0.0.2
[ebuild  N    ] dev-ml/result-1.2
[ebuild  N    ] dev-ml/camlbz2-0.6.0
[ebuild  N    ] dev-ml/ocaml-expat-1.1.0
[ebuild  N    ] dev-ml/dune-1.11.0
[ebuild  N    ] dev-ml/ocaml-ogg-0.5.2
[ebuild  N    ] dev-ml/topkg-0.9.1
[ebuild  N    ] dev-ml/extlib-1.7.1
[ebuild  N    ] dev-ml/ocaml-alsa-0.2.3
[ebuild  N    ] dev-ml/ocaml-mad-0.4.5
[ebuild  N    ] dev-ml/lablgl-1.05-r1
[ebuild  N    ] dev-ml/ocaml-dtools-0.4.1
[ebuild  N    ] dev-ml/ocaml-duppy-0.6.0
[ebuild  N    ] dev-ml/ocaml-bjack-0.1.5-r1
[ebuild  N    ] dev-ml/ocaml-lame-0.3.3-r1
[ebuild  N    ] dev-ml/ocaml-samplerate-0.1.4
[ebuild  N    ] dev-ml/ocaml-cry-0.6.2
[ebuild  N    ] dev-ml/Camomile-1.0.1
[ebuild  N    ] dev-ml/ocamlsdl-0.9.1
[ebuild  N    ] dev-ml/cudf-0.8-r1
[ebuild  N    ] dev-ml/uutf-1.0.1
[ebuild  N    ] dev-ml/ocaml-flac-0.1.4
[ebuild  N    ] dev-ml/ocaml-opus-0.1.2
[ebuild  N    ] dev-ml/ocaml-vorbis-0.7.0
[ebuild  N    ] dev-ml/cmdliner-1.0.2
[ebuild  N    ] dev-ml/lablgtk-2.18.5
[ebuild  N    ] dev-ml/ocamlgraph-1.8.8
[ebuild  N    ] dev-ml/ocaml-mm-0.4.0
[ebuild  N    ] dev-ml/jsonm-1.0.1
[ebuild  N    ] dev-ml/dose3-5.0.1
[ebuild  N    ] dev-ml/opam-1.3.1-r1
[ebuild  N    ] dev-ml/xmlm-1.3.0
[ebuild  N    ] dev-ml/ocaml-xmlplaylist-0.1.4
[ebuild  N    ] media-radio/liquidsoap-1.3.7
```

**Install method**

I added https://github.com/crocket/liquidsoap-1.3.7 on top of https://github.com/SpiderX/portage-overlay

Refer to https://github.com/SpiderX/portage-overlay/issues/7

**Comment by smimram** [comment]
It would be useful to have a gdb stracktrace. Could you make one with
```
% gdb -p <process PID>
> thread apply all bt
```
and give us the output?

**Comment by crocket** [comment]
```
(gdb) thread apply all bt

Thread 7 (Thread 0x7fc06a34e700 (LWP 11616)):
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000561c00299884 in caml_condition_wait ()
#2  0x0000561c0016510a in camlTutils__fun_2755 ()
#3  0x0000561c001638e0 in camlTutils__mutexify_1345 ()
#4  0x0000561c001ff7fd in camlDtools__thread_1841 ()
#5  0x0000561c0020dae9 in camlThread__fun_1564 ()
#6  0x0000561c002ba834 in caml_start_program ()
#7  0x0000561c00298b40 in ?? ()
#8  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7fc06ab4f700 (LWP 11615)):
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000561c00299884 in caml_condition_wait ()
#2  0x0000561c001f5a26 in camlDuppy__queue_inner_3284 ()
#3  0x0000561c0016463f in camlTutils__queue_1688 ()
#4  0x0000561c0016409e in camlTutils__fun_2624 ()
---Type <return> to continue, or q <return> to quit---
#5  0x0000561c0020dae9 in camlThread__fun_1564 ()
#6  0x0000561c002ba834 in caml_start_program ()
#7  0x0000561c00298b40 in ?? ()
#8  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7fc06bb51700 (LWP 11613)):
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000561c00299884 in caml_condition_wait ()
#2  0x0000561c001f5a26 in camlDuppy__queue_inner_3284 ()
#3  0x0000561c00164682 in camlTutils__queue_1688 ()
#4  0x0000561c0016409e in camlTutils__fun_2624 ()
#5  0x0000561c0020dae9 in camlThread__fun_1564 ()
#6  0x0000561c002ba834 in caml_start_program ()
#7  0x0000561c00298b40 in ?? ()
#8  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fc06c352700 (LWP 11612)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000561c00299884 in caml_condition_wait ()
#2  0x0000561c001f5a26 in camlDuppy__queue_inner_3284 ()
#3  0x0000561c00164682 in camlTutils__queue_1688 ()
#4  0x0000561c0016409e in camlTutils__fun_2624 ()
#5  0x0000561c0020dae9 in camlThread__fun_1564 ()
#6  0x0000561c002ba834 in caml_start_program ()
#7  0x0000561c00298b40 in ?? ()
#8  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fc06cb53700 (LWP 11611)):
#0  0x00007fc0781756af in select () from /lib64/libc.so.6
#1  0x0000561c002986b9 in ?? ()
#2  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#3  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fc06d354700 (LWP 11610)):
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#1  0x0000561c00299884 in caml_condition_wait ()
#2  0x0000561c002007e2 in camlDtools__fun_3102 ()
#3  0x0000561c002005ec in camlDtools__mutexify_2152 ()
#4  0x0000561c00200773 in camlDtools__f_2165 ()
#5  0x0000561c0020dae9 in camlThread__fun_1564 ()
#6  0x0000561c002ba834 in caml_start_program ()
#7  0x0000561c00298b40 in ?? ()
#8  0x00007fc078258458 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fc07817e88f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fc079d45940 (LWP 11609)):
#0  0x00007fc07825f13c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000561c00299593 in caml_thread_join ()
#2  0x0000561c0020d973 in camlThread__fun_1555 ()
#3  0x0000561c00226eb5 in camlQueue__iter_1244 ()
#4  0x0000561c00164333 in camlTutils__fun_2651 ()
#5  0x0000561c001ff210 in camlDtools__exec_1580 ()
#6  0x0000561c00216f71 in camlList__iter_1252 ()
#7  0x0000561c001ff1d1 in camlDtools__exec_1580 ()
---Type <return> to continue, or q <return> to quit---
#8  0x0000561c001ff68c in camlDtools__main_1836 ()
#9  0x0000561c001ff928 in camlDtools__catch_1847 ()
#10 0x0000561c00047575 in camlMain__Make_1772 ()
#11 0x0000561c00044c00 in camlRunner__entry ()
#12 0x0000561c0003d679 in caml_program ()
#13 0x0000561c002ba834 in caml_start_program ()
#14 0x0000561c002a03cd in caml_main ()
#15 0x0000561c0003bedc in main ()
```

**Comment by crocket** [comment]
Upgrading dev-ml/ocaml-duppy-0.6.0 to dev-ml/ocaml-duppy-0.8.0 fixed the issue for me.

**Comment by smimram** [comment]
Great, I'll mark as fixed then.

I have changed the requirements on duppy version with 7fb6bbe0eacb3f7f131d01507dda1b9435f5c3b9.

**Comment by crocket** [comment]
Did you actually test ocaml-duppy-0.6.1?

**Comment by smimram** [comment]
I thought you tested 0.6.1, sorry. It actually seems that we need duppy 0.8.0. Fixed in f1ea70844d938bcba526b022ff2a4f04e4e736ce.

**Comment by crocket** [comment]
On https://github.com/savonet/ocaml-duppy/releases,

> 0.7.1 Wake up all queues when shutting down.
> 0.7.3 Avoid race conditions when shutting down.

I guess 0.7.3 is the minimum satisfactory version, but I haven't tested it, yet.

**Comment by smimram** [comment]
The [opam file](https://github.com/savonet/liquidsoap/blob/master/liquidsoap.opam) for Liquidsap explicitly requires 0.8.0 so that someone decided that either Liquidsoap does not build with below versions or that below versions are buggy enough to require this one.
